### ISSUE TITLE
能出一个详细的使用手册吗？  

### ISSUE THREAD

**Issue by longting** [sealyun/cloud-kernel#8]
如何使用此项目？ 能出一个详细的文档放在wiki中吗？ 
cloud-kernel.yaml 这个配置咋弄？ 
![image](https://user-images.githubusercontent.com/5129611/162911251-c992df9e-8e01-4639-b794-871092c208c0.png)

**Comment by cuisongliu** [comment]
使用这个意图是什么？

**Comment by longting** [comment]
打一个k8s的离线安装包

**Comment by cuisongliu** [comment]
sealyun是有的。

**Comment by longting** [comment]
有打离线包的教程吗？

**Comment by cuisongliu** [comment]
sealos 4.0可自己打集群镜像。可以关注一下sealos 4.0
